-- ==============================================================================
-- GUASAPAPP - ESQUEMA DE BASE DE DATOS SUPABASE
-- Ejecuta este script en el SQL Editor de tu panel de control de Supabase.
-- ==============================================================================

-- 1. Tabla de Configuración de IA (API Keys y Proveedor por usuario)
CREATE TABLE IF NOT EXISTS public.ai_configs (
    user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    provider TEXT NOT NULL DEFAULT 'gemini',
    api_key TEXT DEFAULT '',
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Tabla de Configuración de Bots por Contacto
CREATE TABLE IF NOT EXISTS public.bot_configs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    contact_id TEXT NOT NULL,
    persona TEXT NOT NULL,
    active BOOLEAN DEFAULT true NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(user_id, contact_id)
);

-- 3. Tabla de Contactos Favoritos
CREATE TABLE IF NOT EXISTS public.favorites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    contact_id TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(user_id, contact_id)
);

-- 4. Tabla de Historial de Mensajes
CREATE TABLE IF NOT EXISTS public.chat_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    contact_id TEXT NOT NULL,
    message_type TEXT NOT NULL, -- 'incoming', 'outgoing', 'system', 'error'
    sender TEXT,
    text TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Tabla de Personalidades Personalizadas
CREATE TABLE IF NOT EXISTS public.custom_personas (
    id TEXT PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    desc TEXT,
    prompt TEXT NOT NULL,
    avatar TEXT DEFAULT '🎭',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Índices para optimizar búsquedas frecuentes
CREATE INDEX IF NOT EXISTS idx_bot_configs_user_contact ON public.bot_configs(user_id, contact_id);
CREATE INDEX IF NOT EXISTS idx_favorites_user_contact ON public.favorites(user_id, contact_id);
CREATE INDEX IF NOT EXISTS idx_chat_history_user_contact ON public.chat_history(user_id, contact_id);
CREATE INDEX IF NOT EXISTS idx_custom_personas_user ON public.custom_personas(user_id);

-- ==============================================================================
-- ROW LEVEL SECURITY (RLS) - SEGURIDAD POR USUARIO
-- ==============================================================================

ALTER TABLE public.ai_configs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bot_configs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.favorites ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chat_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.custom_personas ENABLE ROW LEVEL SECURITY;

-- Políticas para ai_configs
CREATE POLICY "Users can view their own ai config" 
ON public.ai_configs FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert/update their own ai config" 
ON public.ai_configs FOR ALL USING (auth.uid() = user_id);

-- Políticas para bot_configs
CREATE POLICY "Users can view their own bot configs" 
ON public.bot_configs FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can modify their own bot configs" 
ON public.bot_configs FOR ALL USING (auth.uid() = user_id);

-- Políticas para favorites
CREATE POLICY "Users can view their favorites" 
ON public.favorites FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can modify their favorites" 
ON public.favorites FOR ALL USING (auth.uid() = user_id);

-- Políticas para chat_history
CREATE POLICY "Users can view their chat history" 
ON public.chat_history FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their chat history" 
ON public.chat_history FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Políticas para custom_personas
CREATE POLICY "Users can view their custom personas" 
ON public.custom_personas FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can modify their custom personas" 
ON public.custom_personas FOR ALL USING (auth.uid() = user_id);

